version: '3.3'

services:

  frontend:
    image: vasews/foodgram_frontend:latest
    volumes:
      - ../frontend/:/app/result_build/

  nginx:
    image: nginx:1.19.3
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ../frontend/build:/usr/share/nginx/html/
      - ../docs:/usr/share/nginx/html/api/docs/
      - static_value:/var/html/staticfiles/
      - media_value:/var/html/media/
    depends_on:
      - backend

  db:
    image: postgres:13.2
    container_name: postgresql
    volumes:
      - /var/lib/postgresql/data/
    env_file:
      - .env

  backend:
    image: vasews/foodgram_backend:latest
    command: >
      sh -c "python manage.py collectstatic --noinput &&
             python manage.py migrate &&
             gunicorn foodgram.wsgi:application --bind 0.0.0.0:8000"
    restart: always
    volumes:
      - static_value:/code/staticfiles/
      - media_value:/code/media/
    depends_on:
      - db
    env_file:
      - .env

volumes:
  static_value:
  media_value:
